# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [25]:
import pandas as pd
import datetime as dt
import yfinance as yf

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [15]:
start = dt.datetime(2015, 1, 1)
end = dt.datetime.today()

print(start, end)

2015-01-01 00:00:00 2026-07-07 08:30:13.714937

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

In [16]:
api_key = "YOUR_API_KEY"

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [26]:
df_apple = yf.download("AAPL", start=start, end=end)

df_apple.head()

/tmp/ipykernel_709/2191405593.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_apple = yf.download("AAPL", start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.192604  24.659506  23.754468  24.648441  212818400
2015-01-05  23.511063  24.042136  23.325188  23.962475  257142000
2015-01-06  23.513281  23.772179  23.152592  23.575239  263188400
2015-01-07  23.842978  23.942553  23.610632  23.721273  160423600
2015-01-08  24.759079  24.816612  24.053194  24.170474  237458000

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [27]:
df_apple["stock"] = "AAPL"

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [28]:
df_tsla = yf.download("TSLA", start=start, end=end)
df_tsla["stock"] = "TSLA"

df_ibm = yf.download("IBM", start=start, end=end)
df_ibm["stock"] = "IBM"

df_msft = yf.download("MSFT", start=start, end=end)
df_msft["stock"] = "MSFT"

/tmp/ipykernel_709/893799240.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_tsla = yf.download("TSLA", start=start, end=end)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_709/893799240.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_ibm = yf.download("IBM", start=start, end=end)
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_709/893799240.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_msft = yf.download("MSFT", start=start, end=end)
[*********************100%***********************]  1 of 1 completed

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [29]:
df = pd.concat([df_apple, df_tsla, df_ibm, df_msft])

df.head()

Price,Close,High,Low,Open,Volume,stock,Close,High,Low,Open,...,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,,TSLA,TSLA,TSLA,TSLA,...,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,24.192604,24.659506,23.754468,24.648441,212818400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,23.511063,24.042136,23.325188,23.962475,257142000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,23.513281,23.772179,23.152592,23.575239,263188400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,23.842978,23.942553,23.610632,23.721273,160423600.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,24.759079,24.816612,24.053194,24.170474,237458000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [30]:
df = df.set_index("stock", append=True)
df = df.reorder_levels(["stock", df.index.names[0]])
df = df.sort_index()

df.head()

Price                 Close       High        Low       Open       Volume  \
Ticker                 AAPL       AAPL       AAPL       AAPL         AAPL
stock Date
AAPL  2015-01-02  24.192604  24.659506  23.754468  24.648441  212818400.0
      2015-01-05  23.511063  24.042136  23.325188  23.962475  257142000.0
      2015-01-06  23.513281  23.772179  23.152592  23.575239  263188400.0
      2015-01-07  23.842978  23.942553  23.610632  23.721273  160423600.0
      2015-01-08  24.759079  24.816612  24.053194  24.170474  237458000.0

Price            Close High  Low Open Volume Close High Low Open Volume Close  \
Ticker            TSLA TSLA TSLA TSLA   TSLA   IBM  IBM IBM  IBM    IBM  MSFT
stock Date
AAPL  2015-01-02   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN
      2015-01-05   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN
      2015-01-06   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN
      2015-01-07   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN
      2015-01-08   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN

Price            High  Low Open Volume
Ticker           MSFT MSFT MSFT   MSFT
stock Date
AAPL  2015-01-02  NaN  NaN  NaN    NaN
      2015-01-05  NaN  NaN  NaN    NaN
      2015-01-06  NaN  NaN  NaN    NaN
      2015-01-07  NaN  NaN  NaN    NaN
      2015-01-08  NaN  NaN  NaN    NaN

### Step 7. Create a dataFrame called vol, with the volume values.

In [31]:
vol = df[["Volume"]]

vol.head()

Price                  Volume
Ticker                   AAPL TSLA IBM MSFT
stock Date
AAPL  2015-01-02  212818400.0  NaN NaN  NaN
      2015-01-05  257142000.0  NaN NaN  NaN
      2015-01-06  263188400.0  NaN NaN  NaN
      2015-01-07  160423600.0  NaN NaN  NaN
      2015-01-08  237458000.0  NaN NaN  NaN

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [32]:
weekly_vol = (
    vol.reset_index()
       .groupby(
           ["stock", pd.Grouper(key="Date", freq="W")]
       )["Volume"]
       .sum()
)

print(weekly_vol.head())

Price                   Volume
Ticker                    AAPL TSLA  IBM MSFT
stock Date
AAPL  2015-01-04  2.128184e+08  0.0  0.0  0.0
      2015-01-11  1.133010e+09  0.0  0.0  0.0
      2015-01-18  1.216906e+09  0.0  0.0  0.0
      2015-01-25  7.949480e+08  0.0  0.0  0.0
      2015-02-01  1.863371e+09  0.0  0.0  0.0

### Step 9. Find all the volume traded in the year of 2015

In [35]:
temp_vol = vol.reset_index()
volume_2015 = temp_vol[temp_vol['Date'].dt.year == 2015].set_index(['stock', 'Date'])['Volume'].sum(axis=1).groupby('stock').sum()
print(volume_2015)

stock
AAPL    5.226420e+10
IBM     1.156439e+09
MSFT    9.059456e+09
TSLA    1.632327e+10
dtype: float64