<a href="https://colab.research.google.com/github/nguyenngochieu3127/git-practice/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [ ]:
data = {
    "evolution": ["Ivysaur", "Charmeleon", "Wartortle", "Metapod"],
    "hp": [45, 39, 44, 45],
    "name": ["Bulbasaur", "Charmander", "Squirtle", "Caterpie"],
    "pokedex": ["yes", "no", "yes", "no"],
}

### Step 3. Assign it to a variable called pokemon

In [ ]:
pokemon = pd.DataFrame(data)

pokemon

    evolution  hp        name pokedex
0     Ivysaur  45   Bulbasaur     yes
1  Charmeleon  39  Charmander      no
2   Wartortle  44    Squirtle     yes
3     Metapod  45    Caterpie      no

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [ ]:

pokemon = pokemon[["name", "type", "hp", "evolution", "pokedex"]]

pokemon

         name          type  hp   evolution pokedex
0   Bulbasaur  Grass/Poison  45     Ivysaur     yes
1  Charmander          Fire  39  Charmeleon      no
2    Squirtle         Water  44   Wartortle     yes
3    Caterpie           Bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [ ]:
pokemon["place"] = ["Forest", "Mountain", "Lake", "Garden"]

pokemon

### Step 6. Present the type of each column

In [ ]:
pokemon.dtypes

name         object
type         object
hp            int64
evolution    object
pokedex      object
dtype: object

### BONUS: Create your own question and answer it.

In [ ]:
len(pokemon)

4