# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [16]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

In [17]:
url = "https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv"

### Step 3. Assign it to a variable called

In [18]:
df = pd.read_csv(url)
display(df.head())

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 4.  What is the frequency of the dataset?

In [19]:
print(df.head())

         Date  Total Equity  Domestic Equity  World Equity  Hybrid  \
0  2022-07-06         10167              NaN          3058     NaN
1  2022-07-13          7409              NaN          2808     NaN
2  2022-07-20          3468              NaN           102     NaN
3  2022-07-27         14213              NaN          9667     NaN
4  2022-08-03          9786              NaN          4016     NaN

   Total Bond  Taxable Bond  Municipal Bond  Total
0         842           NaN            2216    NaN
1        2067           NaN             741    NaN
2        -417           NaN             519    NaN
3        8598           NaN            1069    NaN
4        3079           NaN             937    NaN

### Step 5. Set the column Date as the index.

In [20]:
df.set_index("Date", inplace=True)

### Step 6. What is the type of the index?

In [21]:
print(type(df.index))

<class 'pandas.core.indexes.base.Index'>

### Step 7. Set the index to a DatetimeIndex type

In [22]:
df.index = pd.to_datetime(df.index)
print(type(df.index))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [27]:
monthly = df.resample("ME").sum()
monthly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257,0.0,15635,0.0,11090,0.0,4545,0.0
2022-08-31,48663,0.0,32353,0.0,33705,0.0,-1352,0.0
2022-09-30,13775,0.0,10324,0.0,11629,0.0,-1305,0.0
2022-10-31,82879,0.0,55644,0.0,47435,0.0,8209,0.0
2022-11-30,82731,0.0,54314,0.0,37348,0.0,16967,0.0

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [24]:
monthly = monthly.dropna()

monthly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257,0.0,15635,0.0,11090,0.0,4545,0.0
2022-08-31,48663,0.0,32353,0.0,33705,0.0,-1352,0.0
2022-09-30,13775,0.0,10324,0.0,11629,0.0,-1305,0.0
2022-10-31,82879,0.0,55644,0.0,47435,0.0,8209,0.0
2022-11-30,82731,0.0,54314,0.0,37348,0.0,16967,0.0

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [28]:
yearly = monthly.resample("YE").sum()
yearly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-12-31,303756,0.0,197394,0.0,159480,0.0,37913,0.0
2023-12-31,577124,0.0,383911,0.0,301741,0.0,82166,0.0
2024-12-31,501352,0.0,362686,0.0,312480,0.0,50203,0.0
2025-12-31,204465,0.0,126778,0.0,90915,0.0,35862,0.0
2026-12-31,211092,0.0,163602,0.0,137081,0.0,26519,0.0

### BONUS: Create your own question and answer it.

In [26]:
max_year = yearly["Total Equity"].idxmax()
max_value = yearly["Total Equity"].max()

print("Year with highest Total Equity flow:", max_year.year)
print("Value:", max_value)

Year with highest Total Equity flow: 2023
Value: 577124